image: node:6.11.0 # can be upgraded, depending on your node version used

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install npm@5.6.0
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master # or dev, the branch you want to publish